### PR TITLE
Support for Python 3.7

### PR DESCRIPTION
**Pull request by epatters**
Fixes incompatibilities with Python 3.7 related to [re.Pattern](https://bugs.python.org/issue30397) and [PEP 479](https://www.python.org/dev/peps/pep-0479/).

### CODE REVIEW

**Comment by epatters** [comment]
The tests pass on my local machine, but are failing on Travis (for all versions of Python):

```
$ psql -c 'create database blitzdb_test;' -U postgres
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
The command "psql -c 'create database blitzdb_test;' -U postgres" failed and exited with 2 during 
```

**Comment by epatters** [comment]
The build still seems to be broken, but not, I believe, due to any changes that I made.

Is anyone available to review this PR?

**Comment by cjgibson** [comment]
Total shot in the dark, but possible we need to add:

```yaml
services:
  - postgresql
```

To our [Travis config](https://github.com/adewes/blitzdb/blob/master/.travis.yml). Alternatively, it looks like the [Postgres APT that Travis pulls from](https://wiki.postgresql.org/wiki/Apt) claims to no longer support Postgres 9.3, although it looks like the last built package for 9.3 is still available.

**Comment by adewes** [comment]
Hi @cjgibson, thanks for this MR and sorry that it takes a while to review it!

**Comment by adewes** [comment]
Thanks to @epatters as well :)

**Pull request merged**
